name = "assign-plus"
description = "Use `+=` instead of reassigning the variable"
query = """
((assign_exp_object (var_exp) @var (bin_exp_object left: (var_exp) @left_var (bin_op "+") )) @error
  (#eq? @var @left_var))
((assign_exp_object (var_exp) @var (bin_exp_object (bin_op "+") right: (var_exp) @right_var)) @error
  (#eq? @var @right_var))
"""
